//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.HELPS.WebServices.DataAccess
{
    using System;
    
    public partial class BasicSessionBooking
    {
        public int id { get; set; }
        public string studentID { get; set; }
        public int sessionId { get; set; }
        public bool cancel { get; set; }
        public string assisstance { get; set; }
        public string reason { get; set; }
        public Nullable<int> attended { get; set; }
        public Nullable<int> waitingID { get; set; }
        public Nullable<System.DateTime> archived { get; set; }
        public Nullable<int> isgroup { get; set; }
        public string numpeople { get; set; }
        public string lecturercomment { get; set; }
        public string learningissues { get; set; }
        public Nullable<int> islocked { get; set; }
        public string assigntype { get; set; }
        public string assigntypeOther { get; set; }
        public string subject { get; set; }
        public string appointments { get; set; }
        public string appointmentsOther { get; set; }
        public string assisstanceText { get; set; }
    }
}
