//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace UTS.HELPS.WebServices.DataAccess
{
    using System;
    
    public partial class BasicWorkshopBooking
    {
        public int id { get; set; }
        public Nullable<int> workshopID { get; set; }
        public string studentID { get; set; }
        public Nullable<int> canceled { get; set; }
        public Nullable<int> attended { get; set; }
        public Nullable<System.DateTime> archived { get; set; }
    }
}
