#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("HELPS.Resource", IsApplication=true)]

namespace HELPS
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
			global::com.refractored.fab.Resource.Attribute.fab_colorDisabled = global::HELPS.Resource.Attribute.fab_colorDisabled;
			global::com.refractored.fab.Resource.Attribute.fab_colorNormal = global::HELPS.Resource.Attribute.fab_colorNormal;
			global::com.refractored.fab.Resource.Attribute.fab_colorPressed = global::HELPS.Resource.Attribute.fab_colorPressed;
			global::com.refractored.fab.Resource.Attribute.fab_colorRipple = global::HELPS.Resource.Attribute.fab_colorRipple;
			global::com.refractored.fab.Resource.Attribute.fab_shadow = global::HELPS.Resource.Attribute.fab_shadow;
			global::com.refractored.fab.Resource.Attribute.fab_size = global::HELPS.Resource.Attribute.fab_size;
			global::com.refractored.fab.Resource.Color.fab_material_blue_500 = global::HELPS.Resource.Color.fab_material_blue_500;
			global::com.refractored.fab.Resource.Dimension.fab_elevation_lollipop = global::HELPS.Resource.Dimension.fab_elevation_lollipop;
			global::com.refractored.fab.Resource.Dimension.fab_scroll_threshold = global::HELPS.Resource.Dimension.fab_scroll_threshold;
			global::com.refractored.fab.Resource.Dimension.fab_shadow_size = global::HELPS.Resource.Dimension.fab_shadow_size;
			global::com.refractored.fab.Resource.Dimension.fab_size_mini = global::HELPS.Resource.Dimension.fab_size_mini;
			global::com.refractored.fab.Resource.Dimension.fab_size_normal = global::HELPS.Resource.Dimension.fab_size_normal;
			global::com.refractored.fab.Resource.Drawable.fab_shadow = global::HELPS.Resource.Drawable.fab_shadow;
			global::com.refractored.fab.Resource.Drawable.fab_shadow_mini = global::HELPS.Resource.Drawable.fab_shadow_mini;
			global::com.refractored.fab.Resource.Id.mini = global::HELPS.Resource.Id.mini;
			global::com.refractored.fab.Resource.Id.normal = global::HELPS.Resource.Id.normal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton = global::HELPS.Resource.Styleable.FloatingActionButton;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorDisabled = global::HELPS.Resource.Styleable.FloatingActionButton_fab_colorDisabled;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorNormal = global::HELPS.Resource.Styleable.FloatingActionButton_fab_colorNormal;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorPressed = global::HELPS.Resource.Styleable.FloatingActionButton_fab_colorPressed;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_colorRipple = global::HELPS.Resource.Styleable.FloatingActionButton_fab_colorRipple;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_shadow = global::HELPS.Resource.Styleable.FloatingActionButton_fab_shadow;
			global::com.refractored.fab.Resource.Styleable.FloatingActionButton_fab_size = global::HELPS.Resource.Styleable.FloatingActionButton_fab_size;
		}
		
		public partial class Array
		{
			
			// aapt resource value: 0x7f070000
			public const int menu = 2131165184;
			
			static Array()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Array()
			{
			}
		}
		
		public partial class Attribute
		{
			
			// aapt resource value: 0x7f010002
			public const int fab_colorDisabled = 2130771970;
			
			// aapt resource value: 0x7f010001
			public const int fab_colorNormal = 2130771969;
			
			// aapt resource value: 0x7f010000
			public const int fab_colorPressed = 2130771968;
			
			// aapt resource value: 0x7f010003
			public const int fab_colorRipple = 2130771971;
			
			// aapt resource value: 0x7f010004
			public const int fab_shadow = 2130771972;
			
			// aapt resource value: 0x7f010005
			public const int fab_size = 2130771973;
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040002
			public const int charcoal = 2130968578;
			
			// aapt resource value: 0x7f040001
			public const int charcoalLight = 2130968577;
			
			// aapt resource value: 0x7f040000
			public const int fab_material_blue_500 = 2130968576;
			
			// aapt resource value: 0x7f040003
			public const int red = 2130968579;
			
			// aapt resource value: 0x7f040004
			public const int redDark = 2130968580;
			
			// aapt resource value: 0x7f040005
			public const int white = 2130968581;
			
			// aapt resource value: 0x7f040006
			public const int whiteDark = 2130968582;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Dimension
		{
			
			// aapt resource value: 0x7f050004
			public const int fab_elevation_lollipop = 2131034116;
			
			// aapt resource value: 0x7f050003
			public const int fab_scroll_threshold = 2131034115;
			
			// aapt resource value: 0x7f050002
			public const int fab_shadow_size = 2131034114;
			
			// aapt resource value: 0x7f050001
			public const int fab_size_mini = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int fab_size_normal = 2131034112;
			
			static Dimension()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Dimension()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int check = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int close = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int drawEditText = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int fab_shadow = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int fab_shadow_mini = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int Icon = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int @lock = 2130837510;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f090004
			public const int bookedSessionDate = 2131296260;
			
			// aapt resource value: 0x7f090005
			public const int bookedSessionLocation = 2131296261;
			
			// aapt resource value: 0x7f090003
			public const int bookedSessionStatus = 2131296259;
			
			// aapt resource value: 0x7f090002
			public const int bookedSessionTitle = 2131296258;
			
			// aapt resource value: 0x7f090006
			public const int bookedSessionTutor = 2131296262;
			
			// aapt resource value: 0x7f090007
			public const int bookedSessionType = 2131296263;
			
			// aapt resource value: 0x7f09000e
			public const int buttonForgotPassword = 2131296270;
			
			// aapt resource value: 0x7f09000f
			public const int buttonWhatHelps = 2131296271;
			
			// aapt resource value: 0x7f090021
			public const int checkButtons = 2131296289;
			
			// aapt resource value: 0x7f090010
			public const int drawerMain = 2131296272;
			
			// aapt resource value: 0x7f09000b
			public const int editPassword = 2131296267;
			
			// aapt resource value: 0x7f090027
			public const int editPreferredName = 2131296295;
			
			// aapt resource value: 0x7f090029
			public const int editPreferredNumber = 2131296297;
			
			// aapt resource value: 0x7f09000a
			public const int editUtsId = 2131296266;
			
			// aapt resource value: 0x7f090023
			public const int fabCheckCancel = 2131296291;
			
			// aapt resource value: 0x7f090022
			public const int fabCheckOk = 2131296290;
			
			// aapt resource value: 0x7f09002c
			public const int fabInputCancel = 2131296300;
			
			// aapt resource value: 0x7f09002b
			public const int fabInputOk = 2131296299;
			
			// aapt resource value: 0x7f09000d
			public const int fabLogIn = 2131296269;
			
			// aapt resource value: 0x7f09002a
			public const int inputButtons = 2131296298;
			
			// aapt resource value: 0x7f090015
			public const int listMenu = 2131296277;
			
			// aapt resource value: 0x7f090014
			public const int listUpcoming = 2131296276;
			
			// aapt resource value: 0x7f090011
			public const int mainContentFrame = 2131296273;
			
			// aapt resource value: 0x7f090000
			public const int mini = 2131296256;
			
			// aapt resource value: 0x7f090001
			public const int normal = 2131296257;
			
			// aapt resource value: 0x7f090018
			public const int registerView1 = 2131296280;
			
			// aapt resource value: 0x7f090017
			public const int resourceSwitch = 2131296279;
			
			// aapt resource value: 0x7f09001c
			public const int textCheckCourse = 2131296284;
			
			// aapt resource value: 0x7f090020
			public const int textCheckDOB = 2131296288;
			
			// aapt resource value: 0x7f09001d
			public const int textCheckEmail = 2131296285;
			
			// aapt resource value: 0x7f09001b
			public const int textCheckFaculty = 2131296283;
			
			// aapt resource value: 0x7f09001e
			public const int textCheckHomePhone = 2131296286;
			
			// aapt resource value: 0x7f090019
			public const int textCheckInformation = 2131296281;
			
			// aapt resource value: 0x7f09001f
			public const int textCheckMobile = 2131296287;
			
			// aapt resource value: 0x7f09001a
			public const int textCheckName = 2131296282;
			
			// aapt resource value: 0x7f090025
			public const int textCompulsory = 2131296293;
			
			// aapt resource value: 0x7f090024
			public const int textContactInformation = 2131296292;
			
			// aapt resource value: 0x7f090012
			public const int textHelloUser = 2131296274;
			
			// aapt resource value: 0x7f090009
			public const int textLogOnInformation = 2131296265;
			
			// aapt resource value: 0x7f090026
			public const int textPreferredName = 2131296294;
			
			// aapt resource value: 0x7f090028
			public const int textPreferredNumber = 2131296296;
			
			// aapt resource value: 0x7f090016
			public const int textRegisterTitle = 2131296278;
			
			// aapt resource value: 0x7f090013
			public const int textUpcoming = 2131296275;
			
			// aapt resource value: 0x7f090008
			public const int textUtsHelps = 2131296264;
			
			// aapt resource value: 0x7f09000c
			public const int textWrongInput = 2131296268;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int BookedSessionsRow = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int LogOn = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int Main = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int MainLayout = 2130903043;
			
			// aapt resource value: 0x7f030004
			public const int Menu = 2130903044;
			
			// aapt resource value: 0x7f030005
			public const int Register = 2130903045;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f060008
			public const int aboutHelps = 2131099656;
			
			// aapt resource value: 0x7f060000
			public const int applicationName = 2131099648;
			
			// aapt resource value: 0x7f06000d
			public const int checkCourse = 2131099661;
			
			// aapt resource value: 0x7f060011
			public const int checkDOB = 2131099665;
			
			// aapt resource value: 0x7f06000e
			public const int checkEmail = 2131099662;
			
			// aapt resource value: 0x7f06000c
			public const int checkFaculty = 2131099660;
			
			// aapt resource value: 0x7f06000f
			public const int checkHomePhone = 2131099663;
			
			// aapt resource value: 0x7f06000a
			public const int checkInformation = 2131099658;
			
			// aapt resource value: 0x7f060010
			public const int checkMobile = 2131099664;
			
			// aapt resource value: 0x7f06000b
			public const int checkName = 2131099659;
			
			// aapt resource value: 0x7f060012
			public const int contactInformation = 2131099666;
			
			// aapt resource value: 0x7f06001a
			public const int female = 2131099674;
			
			// aapt resource value: 0x7f060006
			public const int forgotPassword = 2131099654;
			
			// aapt resource value: 0x7f06001f
			public const int hello = 2131099679;
			
			// aapt resource value: 0x7f060015
			public const int hintPreferredName = 2131099669;
			
			// aapt resource value: 0x7f060017
			public const int hintPreferredNumber = 2131099671;
			
			// aapt resource value: 0x7f060013
			public const int inputCompulsory = 2131099667;
			
			// aapt resource value: 0x7f06001c
			public const int inputDegree = 2131099676;
			
			// aapt resource value: 0x7f060018
			public const int inputGender = 2131099672;
			
			// aapt resource value: 0x7f060014
			public const int inputPreferredName = 2131099668;
			
			// aapt resource value: 0x7f060016
			public const int inputPreferredNumber = 2131099670;
			
			// aapt resource value: 0x7f060005
			public const int logIn = 2131099653;
			
			// aapt resource value: 0x7f060001
			public const int logOnInformation = 2131099649;
			
			// aapt resource value: 0x7f060019
			public const int male = 2131099673;
			
			// aapt resource value: 0x7f06001b
			public const int other = 2131099675;
			
			// aapt resource value: 0x7f060003
			public const int password = 2131099651;
			
			// aapt resource value: 0x7f06001e
			public const int postgrad = 2131099678;
			
			// aapt resource value: 0x7f060009
			public const int registerTitle = 2131099657;
			
			// aapt resource value: 0x7f06001d
			public const int undergrad = 2131099677;
			
			// aapt resource value: 0x7f060020
			public const int upcoming = 2131099680;
			
			// aapt resource value: 0x7f060002
			public const int utsId = 2131099650;
			
			// aapt resource value: 0x7f060007
			public const int whatHelps = 2131099655;
			
			// aapt resource value: 0x7f060004
			public const int wrongInformation = 2131099652;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f080002
			public const int helpsDialogTheme = 2131230722;
			
			// aapt resource value: 0x7f080001
			public const int helpsFullscreenTheme = 2131230721;
			
			// aapt resource value: 0x7f080000
			public const int helpsTheme = 2131230720;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
		
		public partial class Styleable
		{
			
			public static int[] FloatingActionButton = new int[] {
					2130771968,
					2130771969,
					2130771970,
					2130771971,
					2130771972,
					2130771973};
			
			// aapt resource value: 2
			public const int FloatingActionButton_fab_colorDisabled = 2;
			
			// aapt resource value: 1
			public const int FloatingActionButton_fab_colorNormal = 1;
			
			// aapt resource value: 0
			public const int FloatingActionButton_fab_colorPressed = 0;
			
			// aapt resource value: 3
			public const int FloatingActionButton_fab_colorRipple = 3;
			
			// aapt resource value: 4
			public const int FloatingActionButton_fab_shadow = 4;
			
			// aapt resource value: 5
			public const int FloatingActionButton_fab_size = 5;
			
			static Styleable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Styleable()
			{
			}
		}
	}
}
#pragma warning restore 1591
